services:
  nginx:
    image: nginx:inception
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp_data:/var/www/wordpress
    networks:
      - inception
    restart: always

  mariadb:
    image: mariadb:inception
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - wp_db_data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

  wordpress: #dont forget to add check for fastcgi server
    image: wordpress:inception
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wp_data:/var/www/wordpress
    expose:
      - "9000"
    networks:
      - inception
    env_file:
      - .env
    restart: always

  cadvisor: #dont forget to check https
    image: cadvisor:inception
    build: ./requirements/bonus/cadvisor
    container_name: cadvisor
    ports:
      - "8082:8080"
    volumes:
      - /:/rootfs:ro #some container stats, like filesystem usage, mounts, disk I/O
      - /var/run:/var/run:ro # needed to talk to the container runtime and resolve some live container metadata
      - /sys:/sys:ro # this is where linux exposes cgroups  (CPU/networks stats) ressource usage
      - /var/lib/docker/:/var/lib/docker:ro # for tracking per-container filesystem usage (how much disk space each container takes)
    networks:
      - inception
    restart: always

  website:
    image: website:inception
    build: ./requirements/bonus/website
    container_name: website
    ports:
      - "8083:80"
    networks:
      - inception
    restart: always

  adminer:
    image: adminer:inception
    build: ./requirements/bonus/adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:80"
    networks:
      - inception

volumes:
  wp_db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/isrkik/data/wp_db_data

  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/isrkik/data/wp_data

networks:
  inception:
    driver: bridge
